<a href="https://colab.research.google.com/github/SaralaMuthu/Learntocode/blob/master/sequential_Model_BPD_withfeatures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Implementation of Sequential model [DL] for bipolar data with feature selection[SIFE] [88*62]

https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/

Dataset:
/content/bpd_keras.csv



In [94]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

df=pd.read_csv("/content/bpd_keras.csv",delimiter=',',engine='python')
print(df.shape)
X=df.T
print(X.shape)
df.head()
X.to_csv("/content/bpdfull_kerastest.csv", sep=',',index=False)

(87, 63)
(63, 87)


In [97]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

df=pd.read_csv("/content/bpd_keras.csv",delimiter=',',engine='python')
df.head()
#df.info()

3.357113714  3.983028681  5.940127782  4.139588043  5.814460704  \
0     3.066790     4.025373     6.079582     4.316680     5.490646   
1     2.965364     3.981773     7.030825     4.214055     6.119181   
2     2.795991     3.942487     7.095179     4.081564     6.198601   
3     2.889662     3.826825     5.706106     4.142777     6.015423   
4     2.985508     3.632469     5.679071     4.163714     6.272757   

   4.282461938  7.076563621  3.07370337  4.410611158  9.088235181  ...  \
0     4.276103     7.065319    3.067276     4.684608     9.218441  ...   
1     4.193882     7.032062    2.945055     4.804748     9.076017  ...   
2     4.171021     6.950121    2.896970     4.353537     9.258902  ...   
3     4.053555     7.082191    2.849336     4.486868     8.372573  ...   
4     3.799718     7.099249    2.776286     4.356097     8.221858  ...   

   3.47623891  5.03163978  5.808082474  5.834662803  4.626147075  2.945033804  \
0    3.708093    5.360895     5.279016     5.762554     4.543274     2.951724   
1    3.688301    5.182301     4.921814     5.496268     4.608752     3.208244   
2    3.621796    5.323451     5.381748     5.689574     4.336455     3.281965   
3    3.811783    5.248642     4.535006     5.652107     4.018783     3.296933   
4    3.686616    5.376336     4.492252     5.679525     4.477374     3.164455   

   5.961702048  6.798655247  6.316757921  1  
0     5.902916     7.128693     6.318052  1  
1     6.026238     7.081435     6.159355  0  
2     6.265325     7.072666     6.208074  0  
3     6.188865     6.955535     6.667093  1  
4     6.096672     6.911590     6.587252  1  

[5 rows x 63 columns]

In [98]:
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [109]:
import numpy as np
import pandas as pd
# load the dataset
#dataset = pd.read_csv("/content/bpd_keras.csv",delimiter=',',engine='python')
# split into input (X) and output (y) variables
#X = dataset.iloc[:,:dataset.shape[1]-1]
#y = dataset.iloc[:,-1]
dataset = loadtxt('/content/bpd_keras.csv', delimiter=',')
# split into input (X) and output (y) variables
X = dataset[:,0:62]
y = dataset[:,62]
print(X)
print(y)

[[3.35711371 3.98302868 5.94012778 ... 5.96170205 6.79865525 6.31675792]
 [3.06678956 4.0253732  6.07958195 ... 5.90291591 7.1286931  6.31805199]
 [2.96536409 3.98177261 7.03082471 ... 6.02623835 7.08143546 6.15935461]
 ...
 [2.86692002 3.96292596 6.40021971 ... 6.03084518 7.4100043  6.22513144]
 [3.27459496 3.90180607 6.42684595 ... 5.75556882 7.24032387 6.19611096]
 [3.0342149  3.97071264 5.75817892 ... 6.5821199  7.11966125 5.92849669]]
[1. 1. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1.]


In [152]:
# define the keras model
model = Sequential()
model.add(Dense(12, input_shape=(62,), activation='relu'))
model.add(Dense(62, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [153]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [159]:
# fit the keras model on the dataset
model.fit(X, y, epochs=150, batch_size=5)
_,accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

Epoch 1/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1029 - accuracy: 0.9545
Epoch 2/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1434 - accuracy: 0.9432
Epoch 3/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1036 - accuracy: 0.9545
Epoch 4/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1245 - accuracy: 0.9432
Epoch 5/150
18/18 [==============================] - 0s 4ms/step - loss: 0.2064 - accuracy: 0.9205
Epoch 6/150
18/18 [==============================] - 0s 4ms/step - loss: 0.1064 - accuracy: 0.9545
Epoch 7/150
18/18 [==============================] - 0s 4ms/step - loss: 0.0972 - accuracy: 0.9659
Epoch 8/150
18/18 [==============================] - 0s 3ms/step - loss: 0.1169 - accuracy: 0.9545
Epoch 9/150
18/18 [==============================] - 0s 3ms/step - loss: 0.0852 - accuracy: 0.9545
Epoch 10/150
18/18 [==============================] - 0s 3ms/step - loss: 0.1894 - accuracy: 0.9318
Epoch 11/

In [92]:
predictions = (model.predict(X) > 0.8).astype(int)
# summarize the first 5 cases
for i in range(5):
  print(predictions[i])
 #print('(expected %d)' , predictions[i])

3/3 [==============================] - 0s 150ms/step
[0]
[0]
[0]
[0]
[0]
